export const badge=(text,kind='')=>`<span class="badge ${kind}">${text}</span>`;
export const heading=(title,description,action='')=>`<header class="page-header"><div><h1>${title}</h1><p class="page-description">${description}</p></div>${action}</header>`;
export const field=(name,label,type='text',value='',helper='')=>`<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${value}" ${type==='number'?'min="0" step="1"':''} required>${helper?`<span class="helper">${helper}</span>`:''}</div>`;
export const select=(name,label,values)=>`<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${values.map(v=>`<option>${v}</option>`).join('')}</select></div>`;
export const project=()=>select('project','โครงการ',['INF-026 · ปรับปรุงระบบเครือข่าย','INF-031 · ดูแลระบบสำรองข้อมูล']);
export const note=label=>`<div class="field"><label for="description">${label}</label><textarea id="description" required>เข้าดำเนินงานตามแผนโครงการและตรวจสอบร่วมกับลูกค้า</textarea></div>`;
export const summary=rows=>`<dl class="calc">${rows.map((r,i)=>`<div class="${i===rows.length-1?'total':''}"><dt>${r[0]}</dt><dd>${r[1]}</dd></div>`).join('')}</dl>`;
export const upload=()=>`<div class="field"><label for="receipt">หลักฐานค่าใช้จ่าย</label><div class="upload"><label class="button" for="camera">ถ่ายรูปหลักฐาน</label><input hidden type="file" accept="image/*" capture="environment" id="camera"><input type="file" id="receipt" accept="image/jpeg,image/png,application/pdf"><p>ภาพถ่ายหรือ PDF ไม่เกิน 10 MB ต่อไฟล์</p><div id="file-status" aria-live="polite"></div></div></div>`;
export const form=(body,aside='')=>`<div class="form-layout"><form class="panel" id="request-form">${body}<div class="form-actions"><button type="button" data-draft>บันทึกร่าง</button><button class="primary" type="submit">ตรวจสอบคำขอ</button></div></form><aside class="panel"><h2>สรุปคำขอ</h2>${aside||'<p>หัวหน้าตามสายงานเป็นผู้อนุมัติ</p>'}<p class="muted small" style="margin-top:18px">เก็บนโยบายกับรายการนี้ ไม่คำนวณย้อนหลังโดยอัตโนมัติ</p></aside></div>`;
