import {badge,heading} from './helpers.js';
const rows=[['EX-260923-014','กมลวรรณ ศิริพงษ์','แท็กซี่','INF-026','428.00','รอตรวจสอบ','warning','รอต้นฉบับ','ยังไม่จ่าย'],['EX-260922-011','ธนกร วัฒนกิจ','ค่าทางด่วน','INF-031','185.00','ตรวจสอบแล้ว','success','ได้รับแล้ว','รอจ่าย'],['EX-260921-008','ศุภชัย ภักดี','ค่าเดินทาง','INF-026','584.00','ตรวจสอบแล้ว','success','ไม่ต้องใช้','จ่ายแล้ว'],['EX-260920-006','กมลวรรณ ศิริพงษ์','ค่าโรงแรม','INF-026','1,850.00','ตรวจสอบแล้ว','success','รอต้นฉบับ','จ่ายแล้ว'],['EX-260920-005','ปวีณา รุ่งเรือง','รับรองลูกค้า','INF-031','2,340.00','รอตรวจสอบ','warning','รอต้นฉบับ','ยังไม่จ่าย']];
export const operationsViews={
finance:()=>heading('งานการเงิน','ตรวจเอกสาร ติดตามต้นฉบับ และจัดชุดจ่าย','<a class="button primary" href="?screen=payment">จัดชุดการจ่าย</a>')+`<nav class="tabs" aria-label="คิวการเงิน"><a class="active" href="?screen=finance">รายการทั้งหมด</a><a href="?screen=payment">พร้อมจ่าย 1</a><a href="?screen=finance">ต้นฉบับค้าง 3</a><a href="?screen=settlement">ทดรองครบกำหนด 1</a></nav><div class="filterbar"><input id="search" aria-label="ค้นหารายการหรือพนักงาน" placeholder="ค้นหาเลขที่รายการหรือชื่อพนักงาน"><select aria-label="ประเภทค่าใช้จ่าย"><option>ทุกประเภท</option><option>ค่าเดินทาง</option></select><button id="clear-filter">ล้างตัวกรอง</button></div><div class="table-wrap"><table><caption>ค่าใช้จ่ายสำหรับตรวจแบบ</caption><thead><tr><th scope="col">รายการ / พนักงาน</th><th scope="col">ประเภท / โครงการ</th><th scope="col" class="amount">จำนวนเงิน (บาท)</th><th scope="col">การเงิน</th><th scope="col">หลักฐาน / ต้นฉบับ</th><th scope="col">การจ่าย</th></tr></thead><tbody>${rows.map(r=>`<tr><td><a href="?screen=approval">${r[0]}</a><strong>${r[1]}</strong></td><td><strong>${r[2]}</strong><span class="muted small">${r[3]}</span></td><td class="amount">${r[4]}</td><td>${badge(r[5],r[6])}</td><td><strong class="small">มีหลักฐาน</strong>${badge(r[7],r[7]==='รอต้นฉบับ'?'warning':'')}</td><td>${badge(r[8],r[8]==='จ่ายแล้ว'?'success':'')}</td></tr>`).join('')}</tbody></table></div><div class="table-footer"><span>5 รายการ · ข้อมูลสมมติ</span><span>รวม 5,387.00 บาท</span></div>`,
signin:()=>`<section class="panel signin"><div class="wordmark">INFINITY<span>.</span></div><h1>ระบบพนักงาน</h1><p class="muted">วันลา OT ค่าใช้จ่าย และการเดินทาง<br>สำหรับทีม Infinity Solution Service</p><button class="primary" data-review>เข้าสู่ระบบด้วย Microsoft</button><p class="small muted">ใช้บัญชีบริษัท ไม่มีรหัสผ่านพนักงานแยกต่างหาก</p></section>`,
empty:()=>heading('รายการของฉัน','ติดตามสถานะคำขอและรายการที่ต้องแก้ไข')+`<section class="empty"><h2>ยังไม่มีรายการ</h2><p>เริ่มคำขอวันลา OT ค่าใช้จ่าย หรือการเดินทาง</p><a class="button primary" href="?screen=home">สร้างคำขอ</a></section>`,
error:()=>heading('ส่งคำขอไม่สำเร็จ','ข้อมูลยังอยู่ในหน้านี้ แต่ยังไม่ได้บันทึก')+`<div class="notice error-notice" role="alert"><strong>เชื่อมต่อไม่ได้</strong><p>ตรวจการเชื่อมต่อแล้วลองอีกครั้ง ระบบไม่สร้างรายการซ้ำจากการส่งครั้งเดิม</p><button data-review>ลองอีกครั้ง</button></div><div class="panel"><div class="field"><label for="invalid-hours">ชั่วโมง OT</label><input id="invalid-hours" value="1.5" aria-invalid="true" aria-describedby="hour-error"><span class="error" id="hour-error">ระบุจำนวนชั่วโมงเป็นจำนวนเต็ม เช่น 1 หรือ 2 ชั่วโมง</span></div></div>`,
offline:()=>heading('ขณะนี้ออฟไลน์','กลับมาเชื่อมต่อเพื่อดูหรือทำรายการ')+`<section class="empty"><h2>ยังส่งคำขอหรืออนุมัติไม่ได้</h2><p>ระบบไม่เก็บข้อมูลพนักงานและรายการจ่ายไว้ในแคชออฟไลน์</p><button data-review>ตรวจการเชื่อมต่อ</button></section>`
};
